
# BUSINESS PORTION

\clearpage
\newpage

## Cost

The cost for this project is $99,995, as specified in the budget.
All direct costs will go towards salaries of personnel involved in
software development.

## Institution

The University of Pennsylvania, located in Philadelphia,
has a proud tradition of intellectual rigor and boundary-breaking
scientific innovation that dates back to its founder, Benjamin Franklin.
Penn is one of the world's most powerful research and teaching
institutions, with a research budget last year topping $850 million and
more than 4,300 active faculty members. The scale and interdisciplinary
character of research and teaching sets Penn apart, and the highly
ranked Perelman School of Medicine is one of the top recipients of NIH
funding in the country. As a leading institution for research in medical
image analysis techniques, Penn provides an ideal environment to host
the proposed image processing software development. There is a wealth of
medical imaging focused collaboration across laboratories in the
Departments of Neurology, Psychology, Radiology and Psychiatry. More
specifically, there is a long standing and highly productive
collaboration between the Penn Computing & Science Laboratory (PICSL)
and the Center for Functional Neuroimaging (CfN). Together, these
facilities will provide the necessary resources to execute the proposed
work.

The University of Pennsylvania has a wealth of resources and facilities
that will contribute to the success of the proposed work. In addition to
PICSL and CfN, there are multiple institutes and research centers that
are relevant to the proposed work as their reliance upon image
processing techniques provides an ideal user-base and source of
heterogeneous data to help ensure the generalized utility and robustness
of the software:

* The Center for Advanced Magnetic Resonance Imaging & Spectroscopy (CAMRIS)
* The Neuroscience Neuroimaging Center (NNC)
* Center for Cognitive Neuroscience (CCN)
* Institute on Aging (IOA) Center of Clinical Epidemiology & Biostatistics (CCEB)
* Institute for Translational Medicine & Therapeutics (ITMAT)
* The Mahoney Institute of Neurological Sciences

A recent initiative to consolidate research in neuroimaging and brain
function on the Penn campus will result in nearly all neuroimaging
investigators at Penn being located in newly renovated space in the
Richards and Goddard Laboratories Buildings, a designated National
Historic Landmark designed by the renowned architect Louis Kahn to
facilitate research interactions. Although the Penn campus is already
very compact, consolidating the many faculty members involved in
neuroimaging research will facilitate broader participation in projects,
seminars, workshops, and interdisciplinary training, and will provide an
outstanding environment for trainees to interact with faculty and with
each other.  PICSL will occupy one floor in the D wing of the Richards
building.

## Performance site

The proposed software development effort will take
place at the Penn Image Computing and Science Laboratory (PICSL). Housed
in the Department of Radiology, PICSL is a major research resource in
biomedical image analysis and computing at the Schools of Medicine and
Arts and Sciences of the University of Pennsylvania. PICSL is led by
James Gee, Ph.D., and its faculty members are Brian Avants, Ph.D. and
Paul Yushkevich, Ph.D., Over the past two decades, the laboratory has
collaborated with numerous investigators, including dozens from
extramural organizations, and have provided them with comprehensive
support in cutting-edge image analysis and processing. PICSL is also
part of the graduate groups of the Departments of Computer and
Information Science, Applied Mathematics and Computational Science, and
Bioengineering. It is affiliated with the Centers for Functional
Neuroimaging, for Bioinformatics, for Cognitive Neuroscience and for
Human Modeling and Simulation, the Institutes for Medicine and
Engineering and for Translational Medicine and Therapeutics, the General
Robotics, Automation, Sensing and Perception Laboratory, and the Leonard
Davis Institute of Health Economics, and is a founding member of the
Center for Health Informatics at Penn, the Penn Center for
Musculoskeletal Disorders, and the National Library of Medicine Insight
Consortium. PICSL was the inaugural collaboration partner of the
National Centers for Biomedical Computing, which are specifically
charged to foster translational research in biomedical computing.

PICSL has a long track record of methodological innovation in medical
image analysis as well as a strong commitment to translational research.
In addition to its founding role and continuing support of the Insight
Toolkit (ITK), PICSL leads the development of several significant
open-source tools, including ITK-SNAP, ANTs/ANTsR, Convert3D, PipeDream
and DTI-TK, and serves as as a key contributor to Camino and VoxBo.

Extensive computer facilities for software development and large-scale
data processing are available at PICSL and the CfN data analysis
facility, which houses the computing resources for the NIH funded
Neuroscience Neuroimaging Center (NNC), whose Informatics Core is
managed by Dr. Yushkevich, the PI, and Michael Stauffer is the primary
engineer and system administrator for the Core. The facility includes a
high performance 576-core compute cluster with more than 200TB of
on-line RAID storage with a dedicated tape backup system. The cluster is
located in a University-run commercial-grade server room with redundant
power supplies, UPS power backup systems, fire suppression system and
24-hour restricted access and security. The cluster provides access to a
variety of commercial and customized software packages are available for
statistical analysis, scientific computing, code development, and data
visualization. Additionally, PICSL is equipped with a large number of
dual-processor workstations, all networked via gigabit Ethernet to the
computing cluster and the Internet. A standalone server with multiple
virtual machines, is dedicated to performing automated nightly software
builds for open-source projects. The build system uses the
CMake/CTest/CDash architecture with binaries uploaded to SourceForge and
NITRC. This automated build architecture will be leveraged by the
proposed project.

The NNC Informatics Core operates an XNAT server housed on a modern
multi-core computing server with 32 GB of memory and a dedicated 20TB
RAID. The XNAT server currently houses 3,000 imaging sessions from
multiple projects including large cohorts from the Penn Memory Center,
Penn Epilepsy Center and Penn Frontotemporal Neurodegeneration Center.
The XNAT server is configured as the DICOM send destination for the
Siemens 3T and 7T research MRI scanners operated by CAMRIS. The XNAT
server includes in-house pipelines for data conversion and automatic
multi-atlas brain structure segmentation.

## Open-source software track record

The University of Pennsylvania and
PICSL in particular have an extensive track record of contribution to
open-source projects, including numerous previous contributions to ITK.

* PICSL is a major contributor to ITK. Between 1999 and 2015, PICSL
members have been PIs on four NLM Visual Human Insight Toolkit
contracts. In each case, PICSL all acquisition objectives within the
original delivery and cost schedules. All source code developed by PICSL
under these contracts was released under appropriate open-source
licenses and remains a major part of ITK and related ITK-based
applications. These NLM contracts were:
    * The original NLM ITK contract to Dr. Gee, the head of PICSL, in 1999,
    under which the first-generation ITK image registration and FEM frameworks
    were developed. The 2002
    * ITK-A2D2 contract to Cognitica, Inc., a small company started by Dr.
      Yushkevich, under which ITK-SNAP was first created by integrating
      research software tools SNAP/IRIS developed by Dr. Gerig at the
      University of North Carolina with ITK.
    * The 2002 ITK-A2D2 contract to Dr. Gee to develop a surface-based analysis and
      image normalization environment in ITK.
    * The 2003 ITK-A2D2 contract to Dr. Gee to develop graph-based segmentation
      algorithms in ITK.
    * The 2008 ITK-ARRA contract to Dr. Gee to develop the registration framework in
      ITKv4. This very large effort completely redesigned the registration pipelines,
      introduced efficient diffeomorphic registration algorithms, and  included GPU accelerated
      algorithms.
* PICSL has been awarded three NIH Continued Development and Maintenance of Software grant
  awards for its open-source projects. These awards are:
    * Grant 1R03-EB008200 (PI: Yushkevich) awarded in 2007 to continue the development
      of ITK-SNAP and integrate it into the NITRC
      environment.
    * Grant 1R03-EB009321 (PI: Gee) awarded in 2009 to continue
      the development of DTI-TK, a toolkit for diffusion tensor MRI
      registration and tract-based analysis.
    * Grant 1R01-EB014346 (PI: Yushkevich) awarded in 2010 to continue the development
      of ITK-SNAP.  Under this grant, ITK-SNAP was almost completely rewritten, ported to
      the Qt GUI platform, and extended to support visualization and semi-automatic
      segmentation of multi-modality and multi-component images.
* PICSL members (Gee, Tustison, Avants, Yushkevich) have authored 25 Insight Journal
  articles, including the top-downloaded Insight Journal article N4ITK: Nick's N3 ITK
  Implementation For MRI Bias Field Correction.
* PICSL members are involved in the development of multiple large image-related software
  tools released under open source licenses which, for the most part, follow ITK software
  architecture and coding guidelines.  These are summarized below.

| __Tool__      | __Lead Developer__ |  __Description__  |  __License__  |
|:-------------:|:------------------:|:----------------- |:-------------:|
| ITK-SNAP      | Yushkevich         | GUI tool for 3D image volume\
 visualization, manual and semi-automatic\
  segmentation.      |   GPL         |
| ANTs          | Avants             | Diffeomorphic image registration, tissue\
 classification, thickness analysis.             |   BSD         |
| ANTsR         | Avants             | Multivariate statistical analysis and data\
 visualization in R.            |   BSD         |
| DTI-TK        | Zhang              | Diffusion MRI registration, visualization,\
 tract-based statistical analysis.            |   GPL         |
| Convert3D     | Yushkevich         | Multi-purpose command line tool for\
 2D/3D/4D image processing, format\
  conversion, and analysis.               |   GPL         |
| ASHS/AHEAD    | Yushkevich         | Pipelines for automatic segmentation of\
 anatomical structures in MRI scans using\
  multi-atlas joint label fusion.               |   GPL         |
| HistoloZee    | Adler              | GUI tool for visualization, alignment and\
 segmentation of dense histology stacks and\
  MRI volumes.             |   GPL         |


##  Commitment to open-source software

_Given PICSL’s level of involvement in open-source projects closely aligned with ITK,
and its track record of releasing and maintaining open-source software, we can confidently
commit to making all products of the proposed development open source._
Specifically, the following open-source commitments are made:

* To make all ITK and SimpleITK source code described in the Technical Portion of
the proposal available as part of the ITK repository, and released under
the BSD license.
* To use standard technologies for distribution of source code. This includes
the use of Git/Gerrit/GitHub (for ITK components).
* To adhere to ITK coding, software build, and
software testing practices for all components developed in this project.
* To ensure that all algorithms and technologies integrated into ITK are
not protected by patents that would preclude their inclusion in ITK.

\clearpage
\newpage

# References
