---
title:
author:
date:
bibliography:  references.bib
csl: national-science-foundation-grant-proposals.csl
output:
  pdf_document
geometry:  margin=1in
fontsize: 12pt
---
## Purpose
Two fundamental segmentation approaches in medical imaging are:

* Multi-atlas labeling/segmentation and
* Bayesian segmentation with priors (anatomical or Markov Random Fields (MRF)).

Whereas the latter has a significant developmental history spanning 30+ years,
the former has seen extreme interest in the medical imaging community recently due to
the general success of crowdsourcing solutions to problems.  Although other
segmentation approaches are well-represented within the Insight Toolkit
and SimpleITK (e.g., region growing and level sets), these popular segmentation
approaches are glaringly absent.  This proposal aims to remedy this deficiency.

__Multi-atlas labeling (MAL).__ MAL is the current state-of-the-art for
propagating expert labelings from a reference atlas library onto new instances
of unlabeled data.  Image registration is used to align the atlas library
(images + segmentations)
to a common space.  A statistical model is then used to combine the "guesses" from all the
normalized atlas labels to provide a "best guess" estimate of the target labeling.
Several such algorithms have been developed and much effort has been devoted to
determining relative performance levels.
See, for example, the recent [MICCAI 2012 Grand Challenge and Workshop on Multi-Atlas
Labeling](https://masi.vuse.vanderbilt.edu/workshop2012/index.php/Main_Page)).

The joint fusion (JF) algorithm of [@Wang:2012aa;@Wang:2013aa] is one of the top performing
MAL algorithms.  JF is capable of predicting anatomical labels with
accuracy that rivals expert anatomists [@Yushkevich:2010aa]. It has proven its
effectiveness in lung [@Tustison:2015aa],
[cardiac data](https://masi.vuse.vanderbilt.edu/workshop2013/index.php/Main_Page),
the human brain [@Tustison:2014aa], and in
[multiple modality canine MRI](https://masi.vuse.vanderbilt.edu/workshop2013/index.php/Main_Page).

__Bayesian segmentation with anatomical and/or MRF priors.__
Early statistically-based segmentation work appropriated NASA satellite image processing
software for classification of head tissues in 2-D MR images [@Vannier:1985aa]. Following
this work, many researchers adopted statistical methods for $n$-tissue anatomical brain
segmentation. The Expectation-Maximization (EM) framework is natural [@Dempster:1977aa]
given the "missing data" aspect of this problem. The work described in [@Wells:1996aa]
was one of the first to use EM for finding a locally optimal solution by iterating between
bias field estimation and tissue segmentation.  Core components of this type of work is
the explicit modeling of the tissue intensity values as statistical distributions
[@Cline:1990aa;@Kikinis:1992aa] and the use of MRF modeling [@Geman:1984aa] for regularizing
the classification results [@Held:1997aa].  Recently, reseachers have begun to rely on spatial
prior probability maps of anatomical structures of interest to encode domain knowledge
[@Van-Leemput:1999aa;@Ashburner:2005aa] by providing spatial
prior probability maps and an initial segmentation.  Although this particular segmentation
framework has significant application in the neuroimaging domain, it has also applicable
to other domains such as breast MRI [@Gubern-Merida:2015aa;@Ribes:2014aa] and functional
ventilation of the lung [@Tustison:2011aa].

However, despite the numerous algorithms and other developments which have been proposed
over the years, there are an extremely limited number of software implementations to
perform these types of segmentations *including within the Insight Toolkit and SimpleITK*.
This lack within the segmentation community inspired us to create our own Bayesian-based
segmentation framework [@Avants:2011aa] (denoted as Atropos) which we made publicly
available within our own ANTs repository.  The modular nature of this particular implementation
would fit within the parameters of the ITK library.

## Deliverables
The core contributions of this proposal will include the following deliverables:

1. __A multivariate implementation of the MAL approach described in [@Wang:2012aa].__
 Given the voxelwise estimation of the
optimal labeling, it will be multi-threaded.  It will also handle multi-modal data
as described in [@Wang:2013aa].  Also, as the original description did not constrain
the optimal weights to be strictly positive, a non-negative least squares solution will
be provided as a user-selected option.  This functionality will be encapsulated in the
ITK filter ``itk::WeightedVotingFusionImageFilter``.

2. __A generic architecture for MAP-MRF Bayesian multivariate image segmentation with
     optional spatial priors__.  The proposed framework will encode a family of Bayesian
     segmentation techniques that may be configured in an application-specific manner
     based on developments dating back 30+ years [@Avants:2011aa].  The main ITK
     filter coordinating this framework will be denoted as
     ``itk::AtroposSegmentationImageFilter`` or some varient thereof.  Additional
     contributed ITK classes will allow for a variety of options including:
    * _Initialization:_  Initialization options will allow for 1) ITK-based K-means
      initialization, 2) ITK-based Otsu thresholding, 3) labeled prior image, and 4)
      prior probability images.
    * _Likelihood or observation models:_  Bayesian paradigms for image segmentation
      employ a user selected observation model defining the likelihood term and one
      or more prior probability terms. The likelihood term has been previously
      defined both parametrically and non-parametrically.  Possible options would include
      Gaussian modeling and various Parzen windowing schemes.  The parent class for
      such models will be the ``itk::ListSampleFunction`` with the following child
      classes:
          * ``itk::GaussianListSampleFunction``
          * ``itk::HistogramParzenWindowsListSampleFunction``
          * ``itk::JointHistogramParzenWindowsListSampleFunction``
          * ``itk::JointHistogramParzenShapeAndOrientationListSampleFunction``
          * ``itk::LogEuclideanGaussianListSampleFunction``
          * ``itk::ManifoldParzenWindowsListSampleFunction``
          * ``itk::PartialVolumeGaussianListSampleFunction``
    * _Posterior probability models:_ Application-dependent segmentation needs
     (fully vs. semi-automated) dictate different posterior formulations.  The proposed
     implementation would permit different formulations.
    * _Outlier handling:_  For improved observation model estimation, data is often
    _winsorized_ to minimize the influence of outliers
    (parent class:  ``itk::ListSampleToListSampleFilter``).  Possible options for winsorising
     the sampling would include a robust
     box-plot strategy ``itk::BoxPlotQuantileListSampleFilter``
     and the Grubbs-Rosner method (``itk::GrubbsRosnerListSampleFilter``).
    * _Partial-volume accommodation:_  Discretization often leads to confounds such as
    partial volume effects.  The proposed architecture would include partial-volume
    handling for minimizing such effects (``itk::PartialVolumeGaussianListSampleFunction``).
3. __ITK test code and documentation for the new functionality.__
This proposal may appear ambitious given the modest budget.  However, our
proposal builds upon existing work within ANTs to make these goals achievable.
These classes were written in ITK-style format so integrating
these classes into the ITK library using the gerrit review system will be
straightforward.  However, we will need to write
individual tests for these classes ensuring proper code coverage and function
testing.

4. __SimpleITK integration and generation of tutorial material.__  We will implement appropriate wrapping,
documentation and metadata for SimpleITK.  Beyond these first steps, we will also (most importantly, perhaps)
implement step-by-step tutorial material based on the Simple ITK
platform.

## Benefits

The proposed effort will allow users of ITK, SimpleITK and ITK-based end-user applications
access to fundamental and state-of-the-art segmentation algorithms and corresponding
components which are currently unavailable in a widely distributed platform such as
the Insight Toolkit.  Additionally, the accompanying documentation and tutorial materials
will be of significant benefit for facilitating the accessibility of this new functionality.

## Advantages derived from the use of ITK

We are excited about the opportunity to port these
segmentation frameworks into the core of ITK.  Our prior experience has
shown that the quality and lifespan of such algorithms is greatly
improved when they are merged within the ITK ecosystem.  ITK also provides
one of the best crowdsourcing mechanisms for software debugging and performance-enhancements.
The deep
testing, consistent use of valgrind to find memory defects and
cross-platform CMake-based ctests are all integral to the further
improvement of the C++ backbone of these methods.

## Differences from related prior work

There is a substantial level-set framework within ITK.  There also
exists a relatively under utilized statistical framework that allows
methods such as K-means clustering followed by Markov random field
regularization to be implemented.  However, both of these frameworks
lack the ability to implement truly Bayesian statistical models that
incorporate spatial probability maps and maximize the posterior
probability of a segmentation map explicitly.

## Personnel and resources

The personnel that will implement this plan has extensive background
in general innovative software development with a collective extensive ITK contribution
history.  The project team comprises the following persons:

* Brian B. Avants (PI, 0.6 c.m. effort) is an Assistant Professor of Radiology
at the University of Pennsylvania.  Dr. Avants is the founder and lead
developer for the ITK-based Advanced Normalization Tools (ANTs)
toolkit which is considered by many to be the premier medical image
registration toolkit in the world.  He is also the founder and lead
developer for the ANTsR project---an $R$ interface to the ANTs package
enabling integration of state-of-the-art medical image transformation methods
with advanced statistical and visualization methods.  Among these
qualifications for the proposed project, Dr. Avants is also a found and lead
developer of the Insight Toolkit.    Despite his personal contributions to
code, Dr. Avants has contributed perhaps the most through his leadership
of the ITKv4 development team.  Specifically, his team implemented a
full refactoring of the ITK registration framework.  A few contributions
of this framework include thread safety, the ability to implement
composite transformations, multi-channel registration, extensibility and
addition of cutting edge diffeomorphic transformation models as well as
image similarity metrics for both intensity and
point set features.  In addition, an early version of GPU-based
registration was implemented with OpenCL.

* James C. Gee (Co-investigator, 0.24 c.m. effort) is an Associate Professor of Radiologic
Science in Radiology at the University of Pennsylvania where he currently
serves in several directorships including that of the Penn Image Computing and
Science Laboratory (PICSL).  Dr. Gee's major area of interest is biomedical
image analysis and computing, with active research in all of the quantitative methods
represented, including segmentation, registration, morphometry and shape statistics,
as applied to a variety of organ systems and all of the major and emerging modalities
in biological/biomaterials imaging and in vivo medical imaging. Dr. Gee has an
extended history of software development for medical image analysis.  Most relevant
for this proposal is that Dr. Gee was part of the original ITK development core.
More recently he was the PI on the  ITKv4 registration refactoring efforts.  He has also
obtained several A2D2 grants in collaboration with Drs. Avants and Tustison.

* Paul Yushkevich (Co-investigator, 0.24 c.m. effort) is an Associate Professor of Radiology at the
University of Pennsylvania. His Ph.D. is in Computer Science and he has published over
90 papers on computational medical image analysis and led in the development of a broad
range of methods including continuous medial representation, joint label fusion for
multi-atlas segmentation, learning-based segmentation error correction,
structure-specific analysis of human medial temporal lobe, fusion of dense MRI and
histology, tract-specific analysis of diffusion MRI, bias-free longitudinal MRI
analysis, and others. His unique qualifications for this project arise from his role as
the lead developer of ITK-SNAP since 2003. A company that he started as a graduate
student was the recipient of one of the first-round ITK-A2D2 contracts. This contract
funded the development of ITK-SNAP on the base of the SNAP and IRIS tools developed at
UNC Chapel Hill by his mentor Guido Gerig. In the last decade, he has grown the ITK-SNAP
codebase manyfold, and obtained NIH R01 and R03 grants to support continued ITK-SNAP
development and maintenance. Despite his research, teaching and mentoring
responsibilities, he continues to dedicate at least a third of his time to programming,
most of it in C++ and utilizing ITK. Besides ITK-SNAP, he has developed and contributed
to several other widely used GUI and command line applications, including Convert3D, ANTs,
DTI-TK, ASHS, and HistoloZee. He has expertise in XNAT obtained by setting up, maintaining,
and developing advanced image segmentation pipelines for the XNAT server at the Penn Center
for Functional Neuroimaging, which hosts data from multiple large neuroimaging research
projects.

* Nicholas J. Tustison (consultant) is an Assistant Professor of Radiology
and Medical Imaging at the University of Virginia.   Dr. Tustison has been involved in
various aspects of ITK development since he arrived at PICSL in 2004.  He was initially charged with
fulfillment of the requirements of a 2004-2005 A2D2 grant where
he designed and coded a set of classes to handle graph data types and an
implementation of the popular ``graph cuts'' segmentation algorithm [@Tustison2008].
Other widely-used contributions include generic scattered
data approximation using B-splines [@Tustison2005], N4 bias correction
[@Tustison2009e], and an RGB faux-colormapping framework [@Tustison2008c].


## Budget.

We request a total of $99,955 which includes both direct and indirect costs.

Dr. Avants (5% effort, $7,380.07) will manage the conduct of the project and oversee the project’s successful completion of milestones and deliverables including testing, software development and construction of tutorial material.

Dr. Yushkevich (2% effort, $4,025.49) is a co-inventor of the original Joint Label Fusion algorithm. Dr. Yushkevich will contribute to testing and validating the ITK and SimpleITK implementations of JF.

Dr. Gee (2% effort, $4,846.45) has been involved in the Insight ToolKit since its inception and will contribute his substantial registration expertise and project management skills to the team.

Dr. Tustison (consultant services billed at $46,245) will be the lead software developer for this project. Dr. Tustison is among the top contributors to the Insight ToolKit as judged by the number of lines of code from each author that have survived and are still intact in the current revision of the Insight ToolKit. He is the 11th overall contributor according to this metric as of September 1, 2015.

University of Pennsylvania indirect costs for this project total $37,498.20.

\clearpage
\newpage

## Cost

The cost for this project is $99,995, as specified in the budget.
All direct costs will go towards salaries of personnel involved in
software development.

## Institution

The University of Pennsylvania, located in Philadelphia,
has a proud tradition of intellectual rigor and boundary-breaking
scientific innovation that dates back to its founder, Benjamin Franklin.
Penn is one of the world's most powerful research and teaching
institutions, with a research budget last year topping $850 million and
more than 4,300 active faculty members. The scale and interdisciplinary
character of research and teaching sets Penn apart, and the highly
ranked Perelman School of Medicine is one of the top recipients of NIH
funding in the country. As a leading institution for research in medical
image analysis techniques, Penn provides an ideal environment to host
the proposed image processing software development. There is a wealth of
medical imaging focused collaboration across laboratories in the
Departments of Neurology, Psychology, Radiology and Psychiatry. More
specifically, there is a long standing and highly productive
collaboration between the Penn Computing & Science Laboratory (PICSL)
and the Center for Functional Neuroimaging (CfN). Together, these
facilities will provide the necessary resources to execute the proposed
work.

The University of Pennsylvania has a wealth of resources and facilities
that will contribute to the success of the proposed work. In addition to
PICSL and CfN, there are multiple institutes and research centers that
are relevant to the proposed work as their reliance upon image
processing techniques provides an ideal user-base and source of
heterogeneous data to help ensure the generalized utility and robustness
of the software:

* The Center for Advanced Magnetic Resonance Imaging & Spectroscopy (CAMRIS)
* The Neuroscience Neuroimaging Center (NNC)
* Center for Cognitive Neuroscience (CCN)
* Institute on Aging (IOA) Center of Clinical Epidemiology & Biostatistics (CCEB)
* Institute for Translational Medicine & Therapeutics (ITMAT)
* The Mahoney Institute of Neurological Sciences

A recent initiative to consolidate research in neuroimaging and brain
function on the Penn campus will result in nearly all neuroimaging
investigators at Penn being located in newly renovated space in the
Richards and Goddard Laboratories Buildings, a designated National
Historic Landmark designed by the renowned architect Louis Kahn to
facilitate research interactions. Although the Penn campus is already
very compact, consolidating the many faculty members involved in
neuroimaging research will facilitate broader participation in projects,
seminars, workshops, and interdisciplinary training, and will provide an
outstanding environment for trainees to interact with faculty and with
each other.  PICSL will occupy one floor in the D wing of the Richards
building.

## Performance site

The proposed software development effort will take
place at the Penn Image Computing and Science Laboratory (PICSL). Housed
in the Department of Radiology, PICSL is a major research resource in
biomedical image analysis and computing at the Schools of Medicine and
Arts and Sciences of the University of Pennsylvania. PICSL is led by
James Gee, Ph.D., and its faculty members are Brian Avants, Ph.D. and
Paul Yushkevich, Ph.D., Over the past two decades, the laboratory has
collaborated with numerous investigators, including dozens from
extramural organizations, and have provided them with comprehensive
support in cutting-edge image analysis and processing. PICSL is also
part of the graduate groups of the Departments of Computer and
Information Science, Applied Mathematics and Computational Science, and
Bioengineering. It is affiliated with the Centers for Functional
Neuroimaging, for Bioinformatics, for Cognitive Neuroscience and for
Human Modeling and Simulation, the Institutes for Medicine and
Engineering and for Translational Medicine and Therapeutics, the General
Robotics, Automation, Sensing and Perception Laboratory, and the Leonard
Davis Institute of Health Economics, and is a founding member of the
Center for Health Informatics at Penn, the Penn Center for
Musculoskeletal Disorders, and the National Library of Medicine Insight
Consortium. PICSL was the inaugural collaboration partner of the
National Centers for Biomedical Computing, which are specifically
charged to foster translational research in biomedical computing.

PICSL has a long track record of methodological innovation in medical
image analysis as well as a strong commitment to translational research.
In addition to its founding role and continuing support of the Insight
Toolkit (ITK), PICSL leads the development of several significant
open-source tools, including ITK-SNAP, ANTs/ANTsR, Convert3D, PipeDream
and DTI-TK, and serves as as a key contributor to Camino and VoxBo.

Extensive computer facilities for software development and large-scale
data processing are available at PICSL and the CfN data analysis
facility, which houses the computing resources for the NIH funded
Neuroscience Neuroimaging Center (NNC), whose Informatics Core is
managed by Dr. Yushkevich, the PI, and Michael Stauffer is the primary
engineer and system administrator for the Core. The facility includes a
high performance 576-core compute cluster with more than 200TB of
on-line RAID storage with a dedicated tape backup system. The cluster is
located in a University-run commercial-grade server room with redundant
power supplies, UPS power backup systems, fire suppression system and
24-hour restricted access and security. The cluster provides access to a
variety of commercial and customized software packages are available for
statistical analysis, scientific computing, code development, and data
visualization. Additionally, PICSL is equipped with a large number of
dual-processor workstations, all networked via gigabit Ethernet to the
computing cluster and the Internet. A standalone server with multiple
virtual machines, is dedicated to performing automated nightly software
builds for open-source projects. The build system uses the
CMake/CTest/CDash architecture with binaries uploaded to SourceForge and
NITRC. This automated build architecture will be leveraged by the
proposed project.

The NNC Informatics Core operates an XNAT server housed on a modern
multi-core computing server with 32 GB of memory and a dedicated 20TB
RAID. The XNAT server currently houses 3,000 imaging sessions from
multiple projects including large cohorts from the Penn Memory Center,
Penn Epilepsy Center and Penn Frontotemporal Neurodegeneration Center.
The XNAT server is configured as the DICOM send destination for the
Siemens 3T and 7T research MRI scanners operated by CAMRIS. The XNAT
server includes in-house pipelines for data conversion and automatic
multi-atlas brain structure segmentation.

## Open-source software track record

The University of Pennsylvania and
PICSL in particular have an extensive track record of contribution to
open-source projects, including numerous previous contributions to ITK.

* PICSL is a major contributor to ITK. Between 1999 and 2015, PICSL
members have been PIs on four NLM Visual Human Insight Toolkit
contracts. In each case, PICSL all acquisition objectives within the
original delivery and cost schedules. All source code developed by PICSL
under these contracts was released under appropriate open-source
licenses and remains a major part of ITK and related ITK-based
applications. These NLM contracts were:
    * The original NLM ITK contract to Dr. Gee, the head of PICSL, in 1999,
    under which the first-generation ITK image registration and FEM frameworks
    were developed. The 2002
    * ITK-A2D2 contract to Cognitica, Inc., a small company started by Dr.
      Yushkevich, under which ITK-SNAP was first created by integrating
      research software tools SNAP/IRIS developed by Dr. Gerig at the
      University of North Carolina with ITK.
    * The 2002 ITK-A2D2 contract to Dr. Gee to develop a surface-based analysis and
      image normalization environment in ITK.
    * The 2003 ITK-A2D2 contract to Dr. Gee to develop graph-based segmentation
      algorithms in ITK.
    * The 2008 ITK-ARRA contract to Dr. Gee to develop the registration framework in
      ITKv4. This very large effort completely redesigned the registration pipelines,
      introduced efficient diffeomorphic registration algorithms, and  included GPU accelerated
      algorithms.
* PICSL has been awarded three NIH Continued Development and Maintenance of Software grant
  awards for its open-source projects. These awards are:
    * Grant 1R03-EB008200 (PI: Yushkevich) awarded in 2007 to continue the development
      of ITK-SNAP and integrate it into the NITRC
      environment.
    * Grant 1R03-EB009321 (PI: Gee) awarded in 2009 to continue
      the development of DTI-TK, a toolkit for diffusion tensor MRI
      registration and tract-based analysis.
    * Grant 1R01-EB014346 (PI: Yushkevich) awarded in 2010 to continue the development
      of ITK-SNAP.  Under this grant, ITK-SNAP was almost completely rewritten, ported to
      the Qt GUI platform, and extended to support visualization and semi-automatic
      segmentation of multi-modality and multi-component images.
* PICSL members (Gee, Tustison, Avants, Yushkevich) have authored 25 Insight Journal
  articles, including the top-downloaded Insight Journal article N4ITK: Nick's N3 ITK
  Implementation For MRI Bias Field Correction.
* PICSL members are involved in the development of multiple large image-related software
  tools released under open source licenses which, for the most part, follow ITK software
  architecture and coding guidelines.  These are summarized below.

| __Tool__      | __Lead Developer__ |  __Description__  |  __License__  |
|:-------------:|:------------------:|:----------------- |:-------------:|
| ITK-SNAP      | Yushkevich         | GUI tool for 3D image volume\
 visualization, manual and semi-automatic\
  segmentation.      |   GPL         |
| ANTs          | Avants             | Diffeomorphic image registration, tissue\
 classification, thickness analysis.             |   BSD         |
| ANTsR         | Avants             | Multivariate statistical analysis and data\
 visualization in R.            |   BSD         |
| DTI-TK        | Zhang              | Diffusion MRI registration, visualization,\
 tract-based statistical analysis.            |   GPL         |
| Convert3D     | Yushkevich         | Multi-purpose command line tool for\
 2D/3D/4D image processing, format\
  conversion, and analysis.               |   GPL         |
| ASHS/AHEAD    | Yushkevich         | Pipelines for automatic segmentation of\
 anatomical structures in MRI scans using\
  multi-atlas joint label fusion.               |   GPL         |
| HistoloZee    | Adler              | GUI tool for visualization, alignment and\
 segmentation of dense histology stacks and\
  MRI volumes.             |   GPL         |


##  Commitment to open-source software

_Given PICSL’s level of involvement in open-source projects closely aligned with ITK,
and its track record of releasing and maintaining open-source software, we can confidently
commit to making all products of the proposed development open source._
Specifically, the following open-source commitments are made:

* To make all ITK and SimpleITK source code described in the Technical Portion of
the proposal available as part of the ITK repository, and released under
the BSD license.
* To use standard technologies for distribution of source code. This includes
the use of Git/Gerrit/GitHub (for ITK components).
* To adhere to ITK coding, software build, and
software testing practices for all components developed in this project.
* To ensure that all algorithms and technologies integrated into ITK are
not protected by patents that would preclude their inclusion in ITK.

This proposal may appear ambitious given
the modest budget.  However, our proposal builds upon existing work
within ANTs to make these goals achievable.  Primarily, we will port the
near-ITK quality existing code into the ITK ecosystem for review by
other developers via the Gerrit code review system.  We are strongly
familiar with this system as the team members, particularly lead
developer Nicholas Tustison, regularly contribute to ITK.  Thus, the
effort, here, will follow a natural progression:

* Augment existing ANTs classes that implement prior-based and JF
segmentation with ITK-style tests;

* Pass these for review to Gerrit;

* Implement code refactoring/documentation requested by ITK core;

* Implement appropriate wrapping, documentation and metadata for Simple ITK.

Beyond these first steps, we will also (most importatly, perhaps)
implement step-by-step tutorial material based on the Simple ITK
platform.  

**Simple ITK tutorial material**:  We will employ freely available *real neuroimaging data* on which to base the tutorial material and to promote reproducibility and transparency via open source software. We will employ the Pediatric Template of Brain Perfusion
(PTBP) [at
figshare](http://figshare.com/articles/
The_Pediatric_Template_of_Brain_Perfusion_PTBP_/923555) which includes
free and easy to access multiple modality MRI data with demographics and psychometrics. The data is accompanied by an [organized csv
file](http://files.figshare.com/1699436/ptbp_summary_demographics.csv)
with full data available at [figshare](http://figshare.com/articles/
The_Pediatric_Template_of_Brain_Perfusion_PTBP_/923555).  We will use a
lightly processed version of the data to make examples quick enough for "on the fly" tutorial material.

We will use the sample PTBP subjects to:

* *Tutorial 1:* Build a template based on deformable registration done in Simple ITK

* *Tutorial 2:* Construct template priors with [Joint
Fusion](http://www.ncbi.nlm.nih.gov/pubmed/22732662) and based on freely
available labeled data

* *Tutorial 3:* Normalize and segment the population data based on spatial prior-based
gaussian mixture modeling.

We have prior experience conducting ANTs, ANTsR and ITK tutorials on similar topics. This will all be put together to create a reproducible analysis for a
subset of the PTBP. This material, which will itself be open source, will be invaluable for better introducing the neuroscience and larger biomedical image analysis community to this broadly applicable and powerful quantification
technology.

\clearpage
\newpage

# References
