## Purpose
Two fundamental segmentation approaches in medical imaging are:

* Multi-atlas labeling/segmentation and
* Bayesian segmentation with priors (anatomical or Markov Random Fields (MRF)).

Whereas the latter has a significant developmental history spanning 30+ years,
the former has seen extreme interest in the medical imaging community recently due to
the general success of crowdsourcing solutions to problems.  Although other
segmentation approaches are well-represented within the Insight Toolkit
and SimpleITK (e.g., region growing and level sets), these popular segmentation
approaches are glaringly absent.  This proposal aims to remedy this deficiency.

__Multi-atlas labeling (MAL).__ MAL is the current state-of-the-art for
propagating expert labelings from a reference atlas library onto new instances
of unlabeled data.  Image registration is used to align the atlas library
(images + segmentations)
to a common space.  A statistical model is then used to combine the "guesses" from all the
normalized atlas labels to provide a "best guess" estimate of the target labeling.
Several such algorithms have been developed and much effort has been devoted to
determining relative performance levels.
See, for example, the recent [MICCAI 2012 Grand Challenge and Workshop on Multi-Atlas
Labeling](https://masi.vuse.vanderbilt.edu/workshop2012/index.php/Main_Page)).

The joint fusion (JF) algorithm of [@Wang:2012aa;@Wang:2013aa] is one of the top performing
MAL algorithms.  JF is capable of predicting anatomical labels with
accuracy that rivals expert anatomists [@Yushkevich:2010aa]. It has proven its
effectiveness in lung [@Tustison:2015aa],
[cardiac data](https://masi.vuse.vanderbilt.edu/workshop2013/index.php/Main_Page),
the human brain [@Tustison:2014aa], and in
[multiple modality canine MRI](https://masi.vuse.vanderbilt.edu/workshop2013/index.php/Main_Page).

__Bayesian segmentation with anatomical and/or MRF priors.__
Early statistically-based segmentation work appropriated NASA satellite image processing
software for classification of head tissues in 2-D MR images [@Vannier:1985aa]. Following
this work, many researchers adopted statistical methods for $n$-tissue anatomical brain
segmentation. The Expectation-Maximization (EM) framework is natural [@Dempster:1977aa]
given the "missing data" aspect of this problem. The work described in [@Wells:1996aa]
was one of the first to use EM for finding a locally optimal solution by iterating between
bias field estimation and tissue segmentation.  Core components of this type of work is
the explicit modeling of the tissue intensity values as statistical distributions
[@Cline:1990aa;@Kikinis:1992aa] and the use of MRF modeling [@Geman:1984aa] for regularizing
the classification results [@Held:1997aa].  Recently, reseachers have begun to rely on spatial
prior probability maps of anatomical structures of interest to encode domain knowledge
[@Van-Leemput:1999aa;@Ashburner:2005aa] by providing spatial
prior probability maps and an initial segmentation.  Although this particular segmentation
framework has significant application in the neuroimaging domain, it has also applicable
to other domains such as breast MRI [@Gubern-Merida:2015aa;@Ribes:2014aa] and functional
ventilation of the lung [@Tustison:2011aa].

However, despite the numerous algorithms and other developments which have been proposed
over the years, there are an extremely limited number of software implementations to
perform these types of segmentations *including within the Insight Toolkit and SimpleITK*.
This deficit inspired us to create our own Bayesian-based
segmentation framework [@Avants:2011aa] (denoted as Atropos) which we made publicly
available within our own ANTs repository.  The modular nature of this particular implementation
would fit within the parameters of the ITK library.

## Deliverables
The core contributions of this proposal will include the following deliverables:

1. __A multivariate implementation of the MAL approach described in [@Wang:2012aa].__
 Given the voxelwise estimation of the
optimal labeling, it will be multi-threaded.  It will also handle multi-modal data
as described in [@Wang:2013aa].  Also, as the original description did not constrain
the optimal weights to be strictly positive, a non-negative least squares solution will
be provided as a user-selected option.  This functionality will be encapsulated in the
ITK filter ``itk::WeightedVotingFusionImageFilter``.

2. __A generic architecture for MAP-MRF Bayesian multivariate image segmentation with
     optional spatial priors__.  The proposed framework will encode a family of Bayesian
     segmentation techniques that may be configured in an application-specific manner
     based on developments dating back 30+ years [@Avants:2011aa].  The main ITK
     filter coordinating this framework will be denoted as
     ``itk::AtroposSegmentationImageFilter`` or some varient thereof.  Additional
     contributed ITK classes will allow for a variety of options including:
    * _Initialization:_  Initialization options will allow for 1) ITK-based K-means
      initialization, 2) ITK-based Otsu thresholding, 3) labeled prior image, and 4)
      prior probability images.
    * _Likelihood or observation models:_  Bayesian paradigms for image segmentation
      employ a user selected observation model defining the likelihood term and one
      or more prior probability terms. The likelihood term has been previously
      defined both parametrically and non-parametrically.  Possible options would include
      Gaussian modeling and various Parzen windowing schemes.  The parent class for
      such models will be the ``itk::ListSampleFunction`` with the following child
      classes:
          * ``itk::GaussianListSampleFunction``
          * ``itk::HistogramParzenWindowsListSampleFunction``
          * ``itk::JointHistogramParzenWindowsListSampleFunction``
          * ``itk::JointHistogramParzenShapeAndOrientationListSampleFunction``
          * ``itk::LogEuclideanGaussianListSampleFunction``
          * ``itk::ManifoldParzenWindowsListSampleFunction``
          * ``itk::PartialVolumeGaussianListSampleFunction``
    * _Posterior probability models:_ Application-dependent segmentation needs
     (fully vs. semi-automated) dictate different posterior formulations.  The proposed
     implementation would permit different formulations.
    * _Outlier handling:_  For improved observation model estimation, data is often
    _winsorized_ to minimize the influence of outliers
    (parent class:  ``itk::ListSampleToListSampleFilter``).  Possible options for winsorising
     the sampling would include a robust
     box-plot strategy ``itk::BoxPlotQuantileListSampleFilter``
     and the Grubbs-Rosner method (``itk::GrubbsRosnerListSampleFilter``).
    * _Partial-volume accommodation:_  Discretization often leads to confounds such as
    partial volume effects.  The proposed architecture would include partial-volume
    handling for minimizing such effects (``itk::PartialVolumeGaussianListSampleFunction``).
3. __ITK test code and documentation for the new functionality.__
This proposal may appear ambitious given the modest budget.  However, our
proposal builds upon existing work within ANTs to make these goals achievable.
These classes were written in ITK-style format so integrating
these classes into the ITK library using the gerrit review system will be
straightforward.  However, we will need to write
individual unit tests for these classes ensuring proper code coverage and function testing. We will use simulated data produced on the fly in code.

4. __SimpleITK integration and generation of tutorial material.__  We will implement appropriate wrapping,
documentation and metadata for SimpleITK.  Beyond these first steps, we will also (most importantly, perhaps)
implement step-by-step tutorial material based on the Simple ITK
platform.

## Benefits

The proposed effort will allow users of ITK, SimpleITK and ITK-based end-user applications
access to fundamental and state-of-the-art segmentation algorithms and corresponding
components which are currently unavailable in a widely distributed platform such as
the Insight Toolkit.  Additionally, the accompanying documentation and tutorial materials
will be of significant benefit for facilitating the accessibility of this new functionality.

## Advantages derived from the use of ITK

We are excited about the opportunity to port these
segmentation frameworks into the core of ITK.  Our prior experience has
shown that the quality and lifespan of such algorithms is greatly
improved when they are merged within the ITK ecosystem.  ITK also provides
one of the best crowdsourcing mechanisms for software debugging and performance-enhancements.
The deep
testing, consistent use of valgrind to find memory defects and
cross-platform CMake-based ctests are all integral to the further
improvement of the C++ backbone of these methods.

## Differences from related prior work

There is a substantial level-set framework within ITK.  There also
exists a relatively under utilized statistical framework that allows
methods such as K-means clustering followed by Markov random field
regularization to be implemented.  However, both of these frameworks
lack the ability to implement truly Bayesian statistical models that
incorporate spatial probability maps and maximize the posterior
probability of a segmentation map explicitly.

## Personnel and resources

The personnel that will implement this plan has extensive background
in general innovative software development with a collective extensive ITK contribution
history.  The project team comprises the following persons:

* Brian B. Avants (PI, 0.6 c.m. effort) is an Assistant Professor of Radiology
at the University of Pennsylvania.  Dr. Avants is the founder and lead
developer for the ITK-based Advanced Normalization Tools (ANTs)
toolkit which is considered by many to be the premier medical image
registration toolkit in the world.  He is also the founder and lead
developer for the ANTsR project---an $R$ interface to the ANTs package
enabling integration of state-of-the-art medical image transformation methods
with advanced statistical and visualization methods.  Among these
qualifications for the proposed project, Dr. Avants is also a found and lead
developer of the Insight Toolkit.    Despite his personal contributions to
code, Dr. Avants has contributed perhaps the most through his leadership
of the ITKv4 development team.  Specifically, his team implemented a
full refactoring of the ITK registration framework.  A few contributions
of this framework include thread safety, the ability to implement
composite transformations, multi-channel registration, extensibility and
addition of cutting edge diffeomorphic transformation models as well as
image similarity metrics for both intensity and
point set features.  In addition, an early version of GPU-based
registration was implemented with OpenCL.

* James C. Gee (Co-investigator, 0.24 c.m. effort) is an Associate Professor of Radiologic
Science in Radiology at the University of Pennsylvania where he currently
serves in several directorships including that of the Penn Image Computing and
Science Laboratory (PICSL).  Dr. Gee's major area of interest is biomedical
image analysis and computing, with active research in all of the quantitative methods
represented, including segmentation, registration, morphometry and shape statistics,
as applied to a variety of organ systems and all of the major and emerging modalities
in biological/biomaterials imaging and in vivo medical imaging. Dr. Gee has an
extended history of software development for medical image analysis.  Most relevant
for this proposal is that Dr. Gee was part of the original ITK development core.
More recently he was the PI on the  ITKv4 registration refactoring efforts.  He has also
obtained several A2D2 grants in collaboration with Drs. Avants and Tustison.

* Paul Yushkevich (Co-investigator, 0.24 c.m. effort) is an Associate Professor of Radiology at the
University of Pennsylvania. His Ph.D. is in Computer Science and he has published over
90 papers on computational medical image analysis and led in the development of a broad
range of methods including continuous medial representation, joint label fusion for
multi-atlas segmentation, learning-based segmentation error correction,
structure-specific analysis of human medial temporal lobe, fusion of dense MRI and
histology, tract-specific analysis of diffusion MRI, bias-free longitudinal MRI
analysis, and others. His unique qualifications for this project arise from his role as
the lead developer of ITK-SNAP since 2003. A company that he started as a graduate
student was the recipient of one of the first-round ITK-A2D2 contracts. This contract
funded the development of ITK-SNAP on the base of the SNAP and IRIS tools developed at
UNC Chapel Hill by his mentor Guido Gerig. In the last decade, he has grown the ITK-SNAP
codebase manyfold, and obtained NIH R01 and R03 grants to support continued ITK-SNAP
development and maintenance. Despite his research, teaching and mentoring
responsibilities, he continues to dedicate at least a third of his time to programming,
most of it in C++ and utilizing ITK. Besides ITK-SNAP, he has developed and contributed
to several other widely used GUI and command line applications, including Convert3D, ANTs,
DTI-TK, ASHS, and HistoloZee. He has expertise in XNAT obtained by setting up, maintaining,
and developing advanced image segmentation pipelines for the XNAT server at the Penn Center
for Functional Neuroimaging, which hosts data from multiple large neuroimaging research
projects.

* Nicholas J. Tustison (consultant) is an Assistant Professor of Radiology
and Medical Imaging at the University of Virginia.   Dr. Tustison has been involved in
various aspects of ITK development since he arrived at PICSL in 2004.  He was initially charged with
fulfillment of the requirements of a 2004-2005 A2D2 grant where
he designed and coded a set of classes to handle graph data types and an
implementation of the popular ``graph cuts'' segmentation algorithm [@Tustison2008].
Other widely-used contributions include generic scattered
data approximation using B-splines [@Tustison2005], N4 bias correction
[@Tustison2009e], and an RGB faux-colormapping framework [@Tustison2008c].


## Budget.

We request a total of $99,955 which includes both direct and indirect costs.

Dr. Avants (5% effort, $7,380.07) will manage the conduct of the project and oversee the project’s successful completion of milestones and deliverables including testing, software development and construction of tutorial material.

Dr. Yushkevich (2% effort, $4,025.49) is a co-inventor of the original Joint Label Fusion algorithm. Dr. Yushkevich will contribute to testing and validating the ITK and SimpleITK implementations of JF.

Dr. Gee (2% effort, $4,846.45) has been involved in the Insight ToolKit since its inception and will contribute his substantial registration expertise and project management skills to the team.

Dr. Tustison (consultant services billed at $46,245) will be the lead software developer for this project. Dr. Tustison is among the top contributors to the Insight ToolKit as judged by the number of lines of code from each author that have survived and are still intact in the current revision of the Insight ToolKit. He is the 11th overall contributor according to this metric as of September 1, 2015.

University of Pennsylvania indirect costs for this project total $37,498.20.

\clearpage
\newpage
